#!/usr/bin/perl -w
use FindBin qw($Bin);
my $input =shift;
`perl $Bin/Region_select1.pl $input`;                    	# *.regions
print "step one: region selecting done \n";
`sh $Bin/seq_out.sh`;             			# *.seq
`sh $Bin/primer_probe.sh`;					# *.p1 *.p2 *.probe
print "step two: primers probe selecting done\n";
`sh $Bin/primer_probe_blast.sh $input`;
print "step three: Blasting is over\n";
system "sh $Bin/Bsp_all_to_xls.sh";
print "step four: Bsp to xls done\n";
`rm *.bsp`;
`sh $Bin/seq_out2.sh`	;				# *.seq2
`perl $Bin/paste_seq_xls.pl`;					# #.out2
print "step five: is  done\n";
`sh $Bin/ppp_sort_uniq.sh`;
print "step six: sorting and uniqing is done\n";
`perl $Bin/paste_p1p2.pl`;
print "step seven: HEBING is done\n";
`sh $Bin/rank_primer_probe.sh`;
print "step eight: Ranking is done\n";
`sh $Bin/ouput.sh`;
`sh $Bin/final.sh`;
print "step final: is done\nNow I will automatically select  the ppp to continue next step\n";
`mkdir txt`;
`cp *.txt $input ./txt`;
$dir = $ENV{'PWD'};
chdir("${dir}/txt");
`perl $Bin/stage2.pl $input`;
print "My work is done\n";
